---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2017-11-27 at 2-25-38 pm/Screen Shot 2017-11-27 at 2-25-38
      pm.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/176118/articles/212065/master/file/figures/Screen%20Shot%202017-11-27%20at%202-25-38%20pm/Screen%20Shot%202017-11-27%20at%202-25-38%20pm.png"
    folder_url: "/users/176118/articles/212065/master/folder/figures/Screen Shot 2017-11-27
      at 2-25-38 pm"
