---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Ecosystem health model/Ecosystem health model.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/176118/articles/212065/master/file/figures/Ecosystem%20health%20model/Ecosystem%20health%20model.png"
    folder_url: "/users/176118/articles/212065/master/folder/figures/Ecosystem health
      model"
