---
version: 2
multicolumn: false
web-width: 1000px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/STAGES, steps/STAGES, steps.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/176118/articles/212065/master/file/figures/STAGES,%20steps/STAGES,%20steps.png"
    folder_url: "/users/176118/articles/212065/master/folder/figures/STAGES, steps"
