---
version: 2
multicolumn: false
web-width: '700'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/criteria table 2/criteria table 4.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/176118/articles/212065/master/folder/figures/criteria table
      2"
    url: "/users/176118/articles/212065/master/file/figures/criteria%20table%202/criteria%20table%204.png"
